tomcat:
 ajp:
  port: 8009
  enabled: false

spring:
 datasource:
  url: jdbc:mysql://192.168.2.106:56243/alltagshelfer
  testWhileIdle: true
  validationQuery: SELECT 1
  driver-class-name: com.mysql.jdbc.Driver
  username: alltagshelfer
  password: vXRRbaXsFFHpBs9g
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: validate
   naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
 properties:
  hibernate:
   dialect: org.hibernate.dialect.MySQL5Dialect