tomcat:
 ajp:
  port: 8009
  enabled: false
  
# SERVER CONFIG:
#
#spring:
# datasource:
#  url: jdbc:mysql://alltagshelfer.ddns.net:56243/alltagshelfer
#  testWhileIdle: true
#  validationQuery: SELECT 1
#  driver-class-name: com.mysql.jdbc.Driver
#  username: alltagshelfer
#  password: vXRRbaXsFFHpBs9g
# jpa:
#  show-sql: true
#  hibernate:
#   ddl-auto: update
#   naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
# properties:
#  hibernate:
#   dialect: org.hibernate.dialect.MySQL5Dialect
#
# LOCAL DEVELOPMENT CONFIG:
#
spring:
 datasource:
  driverClassName: org.apache.derby.jdbc.EmbeddedDriver
  url: jdbc:derby:memory:myDb;create=true
  username: sa
  password: sa
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: update
   naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
 properties:
  hibernate:
   dialect: org.hibernate.dialect.DerbyDialect
 mvc:
  view:
   prefix: /WEB-INF/templates/
   suffix: .jsp
 servlet:
  multipart:
   max-file-size: 25MB
   max-request-size : 25MB